//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class isu_form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public isu_form()
        {
            this.isu_data = new HashSet<isu_data>();
        }
    
        public int order_number { get; set; }
        public string request_number { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> requset_for { get; set; }
        public Nullable<int> wharehouse_responsible { get; set; }
        public Nullable<int> reiceved_by { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isu_data> isu_data { get; set; }
    }
}
