//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.dmg_data = new HashSet<dmg_data>();
            this.ins_data = new HashSet<ins_data>();
            this.isu_data = new HashSet<isu_data>();
            this.re_data = new HashSet<re_data>();
        }
    
        public int item_id { get; set; }
        public string item_name { get; set; }
        public string manufacturer { get; set; }
        public string mfn_part_sn { get; set; }
        public string item_woner { get; set; }
        public string item_type { get; set; }
        public Nullable<System.DateTime> item_date { get; set; }
        public Nullable<System.DateTime> item_time { get; set; }
        public string sku { get; set; }
        public string wharehouse { get; set; }
        public string located_at { get; set; }
        public double starting_balance { get; set; }
        public string unit { get; set; }
        public string min_stock { get; set; }
        public string avg_price { get; set; }
        public string asset_code { get; set; }
        public string owner_remark { get; set; }
        public string status_item { get; set; }
        public string requset_type { get; set; }
        public string remarks { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dmg_data> dmg_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ins_data> ins_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isu_data> isu_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<re_data> re_data { get; set; }
    }
}
